name: Canvas Notifier Cron

on:
  workflow_dispatch: # Allows manual and external(with API) executions.

jobs:
  check-canvas-announcements:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notifier script
        env:
          CANVAS_FEEDS: ${{ secrets.CANVAS_FEEDS }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python notifier.py

      - name: Save state (Commit)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 chore: update processed announcements record"
          file_pattern: "processed_ids.json"